name: Temp

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run:  make func
      - run:  ./func version
      - run:  ./func version --verbose
